---
repos:
  - repo: https://github.com/lyz-code/yamlfix/
    rev: 1.16.0
    hooks:
      - id: yamlfix
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: check-json
      - id: pretty-format-json
        args:
          - --autofix
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=.md
      - id: check-added-large-files
        args:
          - --maxkb=512
      - id: check-toml
      - id: mixed-line-ending
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.41.0
    hooks:
      - id: markdownlint-fix
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args:
          - --baseline
          - .secrets.baseline
        exclude: package.lock.json
