---
version: '3'
services:
  traefik:
    image: traefik:v2.10.7@sha256:c5181ddf303f1ccfd4bd6d1d9c4867b0500efb6089a0f9ccb16612438f6e934f
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=<Your Email>"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - 443:443
      - 80:80
      - 8080:8080
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always
  umami:
    image: ghcr.io/umami-software/umami:postgresql-v2.5.0@sha256:59acdba71970aa1b8219003aa616dc0ec886a8eed241e546dbec841653c1bec0
    container_name: "umami"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`umami.<Your Domain>`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=myresolver"
    environment:
      DATABASE_URL: postgresql://umami:<DB Password>@db:5432/umami
      DATABASE_TYPE: postgresql
      HASH_SALT: <Replace me with a random string>
    depends_on:
      - db
    restart: always
    init: true
  db:
    image: postgres:16.1-alpine3.18@sha256:c9d6afcf22c5b007caf282a59aba463838aa1bf5c4511682c1f07cb6c54e8376
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: <DB Password>
    volumes:
      #- <https://github.com/umami-software/umami/blob/master/sql/schema.postgresql.sql>:/docker-entrypoint-initdb.d/schema.postgresql.sql:ro
      - umami-db-data:/var/lib/postgresql/data
    restart: always
volumes:
  umami-db-data:
  letsencrypt:
